In [1]:
import numpy as np

# Task 1.1 Environmental Sensor Analysis

A sensor records hourly temperatures over 72 hours. Some readings are corrupted and contain unrealistic values.

In [2]:
import numpy as np

np.random.seed(42)

raw_temperatures = np.random.normal(loc=24.0, scale=3.0, size=72)

# Simulated corrupt readings
raw_temperatures[[5, 12, 28, 45, 60]] = [99.9, -15.0, 88.8, -50.0, 102.4]

#### Tasks

1. Create a boolean mask for valid temperatures.

In [4]:
bool_mask = (raw_temperatures >= 15.0) & (raw_temperatures <= 40.0)

2. Replace all invalid values with the median of the valid temperatures.

In [5]:
# Extracting valid temperatures
valid_temperatures = raw_temperatures[bool_mask]

In [6]:
print(valid_temperatures)

[25.49014246 23.5852071  25.94306561 28.56908957 23.29753988 28.73763845
 26.30230419 22.59157684 25.62768013 22.60974692 22.60281074 18.26015927
 18.8252465  22.31313741 20.96150664 24.942742   21.27592777 19.7630889
 28.39694631 23.3226711  24.20258461 19.72575544 22.36685183 24.33276777
 20.54701927 25.12709406 23.12491875 22.19488016 29.55683455 23.95950833
 20.82686721 26.46763474 20.33746905 24.62659079 18.12098963 20.01544185
 24.59058371 26.21539974 24.51410484 23.65305515 23.09668891 19.56443403
 22.61808369 27.17136668 25.03085487 18.71087953 24.97225191 22.84475316
 21.969234   25.83502887 27.09299857 26.79384036 21.48234743 23.07236287
 24.99379029 26.92663538 23.44302307 20.68099508 20.41138013 26.43757747
 28.06872009 23.78396964 27.01059869 25.08490808 22.06464074 25.08418682
 28.6141097 ]


In [7]:
# Computing the median of valid values
median_value = np.median(valid_temperatures)

In [8]:
print(median_value)

23.65305515283528


In [9]:
# Replacing invalid values using vectorization
cleaned_temperatures = np.where(bool_mask, raw_temperatures, median_value)

In [10]:
print(cleaned_temperatures)

[25.49014246 23.5852071  25.94306561 28.56908957 23.29753988 23.65305515
 28.73763845 26.30230419 22.59157684 25.62768013 22.60974692 22.60281074
 23.65305515 18.26015927 18.8252465  22.31313741 20.96150664 24.942742
 21.27592777 19.7630889  28.39694631 23.3226711  24.20258461 19.72575544
 22.36685183 24.33276777 20.54701927 25.12709406 23.65305515 23.12491875
 22.19488016 29.55683455 23.95950833 20.82686721 26.46763474 20.33746905
 24.62659079 18.12098963 20.01544185 24.59058371 26.21539974 24.51410484
 23.65305515 23.09668891 19.56443403 23.65305515 22.61808369 27.17136668
 25.03085487 18.71087953 24.97225191 22.84475316 21.969234   25.83502887
 27.09299857 26.79384036 21.48234743 23.07236287 24.99379029 26.92663538
 23.65305515 23.44302307 20.68099508 20.41138013 26.43757747 28.06872009
 23.78396964 27.01059869 25.08490808 22.06464074 25.08418682 28.6141097 ]


3. Calculate and print Mean, SD, Variance

In [11]:
mean_val = np.round(np.mean(cleaned_temperatures), 2)
std_val = np.round(np.std(cleaned_temperatures), 2)
var_val = np.round(np.var(cleaned_temperatures), 2)

In [12]:
print("Mean:", mean_val)
print("Standard Deviation:", std_val)
print("Variance:", var_val)

Mean: 23.74
Standard Deviation: 2.69
Variance: 7.24


---

# Task 1.2: Matrix Slicing & Strided Operations


In [13]:
grid = np.arange(10, 74).reshape(8, 8)

In [14]:
print(grid)

[[10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25]
 [26 27 28 29 30 31 32 33]
 [34 35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57]
 [58 59 60 61 62 63 64 65]
 [66 67 68 69 70 71 72 73]]


1. Extract the center 4 × 4 portion of the matrix.

In [17]:
center = grid[2:6, 2:6]

In [18]:
print(center)

[[28 29 30 31]
 [36 37 38 39]
 [44 45 46 47]
 [52 53 54 55]]


2. Extract the last column using a single slicing statement.

In [19]:
last_column = grid[:, -1]

In [20]:
print(last_column)

[17 25 33 41 49 57 65 73]


3. Create a 4 × 4 downsampled matrix by selecting every second row and every second column.

In [24]:
#Every second row and column
downsampled_matrix = grid[::2, ::2]

In [25]:
print(downsampled_matrix)

[[10 12 14 16]
 [26 28 30 32]
 [42 44 46 48]
 [58 60 62 64]]


---

# Part 2: Sliding Median Filter

In [26]:
signal = np.array([10, 11, 99, 12, 13, -45, 14, 15, 16])

In [27]:
#Creating a copy

In [28]:
filtered_signal = signal.copy()

2. Write a loop that iterates from index 1 to 7.
3. For each position:

In [29]:
for i in range(1, len(signal) - 1):
    
    # Extract window [i-1, i, i+1]
    window = signal[i-1:i+2]
    
    # Compute median
    median_value = np.median(window)
    
    # Update filtered signal
    filtered_signal[i] = median_value

Print both:

In [30]:
print("Original Signal:", signal)
print("Filtered Signal:", filtered_signal)

Original Signal: [ 10  11  99  12  13 -45  14  15  16]
Filtered Signal: [10 11 12 13 12 13 14 15 16]


The median filter removes spikes in the signal by replacing each value with the median of its neighboring values within a sliding window. In this case, extreme values such as 99 and -45 are significantly higher or lower than their surrounding values. When the median is computed over a window of three elements, these outliers do not affect the result because the median selects the middle value after sorting, effectively ignoring extreme deviations.

This makes the median filter particularly effective for removing impulse noise or sudden spikes. In contrast, using the mean would be influenced by these extreme values, causing the filtered result to still be distorted. Therefore, the median filter provides a more robust and reliable smoothing technique for noisy signals with outliers.

---